language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
